<?php

namespace SuperBundle\Repository;

/**
 * VersionnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionnementRepository extends \Doctrine\ORM\EntityRepository
{
    
}
